name: Run Bambda Checker on Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  update_readmes:
    if: github.event.pull_request.merged 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          ssh-key: ${{secrets.ACTION_PRIVKEY}}
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Validate Bambdas & update READMEs
        run: |
          [ $(sha256sum BambdaChecker-1.2.jar | awk '{ print $1 }') = '30959be3dce023d3b53c4e2507b9db7fed8bfe41501b14bb8c0d4d3a0a50fd71' ]
          java -jar BambdaChecker-1.2.jar
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update README.md files" || true
          git push || true
